version: '3'

services:
  webserver:
    image: periscuelo/nginx-ssl
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
